apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data 
  namespace: mateapp
spec:
  storageClassName: standart
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: hostpath